version: '2'

volumes:
  cadmovies-data:
    driver: local
  cadmovies-cache:
    driver: local

services:
  mysql:
    image: mysql:5.7
    container_name: cadmoviesdb
    volumes:
      - cadmovies-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=cadmovies
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret

  # Redis
  cache:
    image: redis:3.2
    container_name: cadmoviesredis
    command: --appendonly yes
    volumes:
      - cadmovies-cache:/data
    ports:
      - "6379:6379"

  # Laravel
  app:
    image: ambientum/php:7.3-nginx
    container_name: cadmoviesapp
    volumes:
      - ./:/var/www/app
    ports:
      - "8000:8080"
    links:
      - mysql
      - cache
